version: "3"
services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - $HTTP_PORT:80
    environment:
      HTTP_PORT: 80
    volumes:
      - .:/app
    command: make prepare-and-run-jar

  db:
    image: "postgres:14"
    ports:
      - $DATABASE_PORT:5432
    environment:
      POSTGRES_DB: health_patient
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
